version: '3'
services:
  serenity_report_webservices:
    container_name: serenity_report_webservices
    image: "report_ws:$BUILD_NUMBER"
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "8889:80"